name: NewLeafMN
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2721353811211884
title: 'New Leaf Landscaping & Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#010101'
    - '#363f08'
    - '#bebebe'
    - '#909090'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
